const { buildCharacterSkillsPrompt } = require("./buildCharacterSkillsPrompt");

function buildRuntimeAdventurePrompt(input = {}) {
  const modelGenre = input.genre || "奇幻遺跡";
  const characterPrompt = input.characterPrompt || "一位謹慎但勇敢的冒險者。";
  const adventurePrompt = input.adventurePrompt || "設計一段短篇地下城冒險。";
  const roomCount = Number(input.roomCount) || 5;
  const difficulty = Number(input.difficulty) || 4;

  return [
    "你是 RPG 文字冒險 Content Designer。請只輸出一個可直接執行的 JSON object。",
    "語言使用繁體中文；所有 id 使用 snake_case 英文，不要使用中文、dash 或空白。",
    "",
    "玩家設定：",
    characterPrompt,
    "",
    "冒險需求：",
    `類型：${modelGenre}`,
    `房間數：${roomCount}`,
    `難度：${difficulty}/10`,
    adventurePrompt,
    "",
    "JSON schema 必須符合：",
    "- root 欄位：initialRoomId, winCondition, player, rooms, items, monsters, skills",
    "- winCondition: { type: \"return_with_item\", requiredItemId, returnRoomId, requiredBossDefeated }",
    "- player: hp, maxHp, mp, maxMp, attack, defense, level, skills",
    "- rooms 是 object map，key 必須等於 room.id；房間數必須剛好等於指定房間數。",
    "- 每個 room: id, name, description, kind, challenge, ascii, exits, items, monster",
    "- room.kind 必須是 start/combat/puzzle/treasure/rest/key/boss/lore 其中之一。",
    "- 每個 room 必須有 gameplay function：items、monster、challenge、start/rest/lore/boss 其中至少一種。",
    "- exits 只能使用 north/south/east/west，且每個出口只能指向存在的 room id。",
    "- exits 必須雙向一致，所有房間必須可從 initialRoomId 抵達。",
    "- room.items 只能引用 items 中存在的 id；room.monster 必須是 null 或引用 monsters 中存在的 id。",
    "- 至少 1 個普通怪物、1 個 Boss、1 個補血道具、1 個任務關鍵物品。",
    "- 至少 1 個 equipment item，且放在 Boss 前可取得的 treasure/key/rest 房間。",
    "- 至少 1 個 puzzle/challenge，使用 room.challenge 描述。",
    "- 至少 2 個可準備 Boss 的資源：補血、裝備、rest、hint、key 皆可。",
    "- Boss 必須守著任務關鍵物品所在房間；winCondition.requiredItemId 必須是該任務物品。",
    "- Boss 不可以出現在 initialRoomId，也不可以太強；Lv1 玩家應能靠補給、技能、裝備獲勝。",
    "- items 每個物件必須有 id, name, description, type, usageHint；consumable 必須有 effect.hp。",
    "- equipment item 必須 type: \"equipment\"，並包含 slot 與 stats。",
    "- equipment slot 只能是 weapon/armor/accessory。",
    "- equipment stats 可使用 attack/defense/maxHp/maxMp。",
    "- monsters 每個物件必須有 id, name, maxHp, hp, attack, defense, expReward, drops, description。",
    buildCharacterSkillsPrompt(),
    "",
    "room.challenge schema:",
    "{",
    "  \"type\": \"puzzle\" | \"locked_door\" | \"trap\" | \"riddle\",",
    "  \"description\": \"...\",",
    "  \"requiredItemId\": \"optional_key_id_or_null\",",
    "  \"solutionHint\": \"...\",",
    "  \"rewardItemIds\": [\"optional_reward_item_id\"]",
    "}",
    "",
    "5-room pacing template:",
    "1. start room: intro and basic hint.",
    "2. combat or puzzle room: first gameplay obstacle.",
    "3. key or treasure room: equipment, key item, or useful consumable.",
    "4. rest/lore/puzzle room: preparation before Boss.",
    "5. boss room: Boss + quest item.",
    "",
    "If roomCount is 6-8, add optional treasure, puzzle, elite combat, or rest rooms before Boss.",
    "",
    "CRITICAL object map rules:",
    "- \"rooms\" MUST be a JSON object map, NOT an array.",
    "- \"items\" MUST be a JSON object map, NOT an array.",
    "- \"monsters\" MUST be a JSON object map, NOT an array.",
    "- \"skills\" MUST be a JSON object map, NOT an array.",
    "- The object key MUST exactly match the inner \"id\".",
    "",
    "Correct items format:",
    "\"items\": {",
    "  \"healing_potion\": {",
    "    \"id\": \"healing_potion\",",
    "    \"name\": \"療癒藥水\",",
    "    \"type\": \"consumable\",",
    "    \"description\": \"恢復生命的藥水。\",",
    "    \"usageHint\": \"受傷時使用。\",",
    "    \"effect\": { \"hp\": 10 }",
    "  }",
    "}",
    "",
    "Wrong items format, do not use:",
    "\"items\": [",
    "  { \"id\": \"healing_potion\" }",
    "]",
    "",
    "平衡建議：",
    "- 難度越高，怪物 HP/attack 可提高，但仍要讓玩家有機會完成。",
    "- 避免把勝利物品放在初始房間。",
    "- 每個房間 description 要能支持 Map / Story UI 直接顯示。",
    "",
    "輸出格式：",
    "- 第一個字元必須是 {，最後一個字元必須是 }。",
    "- 不要 markdown code block、不要說明、不要註解。",
  ].join("\n");
}

module.exports = {
  buildRuntimeAdventurePrompt,
};
