const { buildCharacterSkillsPrompt } = require("./buildCharacterSkillsPrompt");

function buildCharacterPreviewPrompt(input = {}) {
  return [
    "You are an RPG character designer. Output one JSON object only.",
    "Use Traditional Chinese for text fields. Use safe snake_case English ids.",
    "",
    "Input:",
    `genre: ${input.genre || "奇幻地下城"}`,
    `difficulty: ${Number(input.difficulty) || 4}`,
    `characterPrompt: ${input.characterPrompt || "一位適合短篇地下城冒險的角色"}`,
    "",
    "Schema:",
    "{",
    "  \"id\": \"character_id\",",
    "  \"name\": \"...\",",
    "  \"title\": \"...\",",
    "  \"summary\": \"...\",",
    "  \"background\": \"...\",",
    "  \"personality\": \"...\",",
    "  \"attributes\": { \"maxHp\": 30, \"maxMp\": 10, \"attack\": 6, \"defense\": 2 },",
    "  \"skills\": [",
    "    { \"id\": \"basic_skill_id\", \"name\": \"...\", \"role\": \"damage\", \"mpCost\": 0, \"damage\": 7, \"description\": \"...\", \"flavorText\": \"...\" }",
    "  ],",
    "  \"starterEquipment\": [",
    "    { \"id\": \"starter_weapon\", \"name\": \"...\", \"type\": \"equipment\", \"slot\": \"weapon\", \"stats\": { \"attack\": 1 }, \"description\": \"...\", \"usageHint\": \"use starter_weapon\", \"flavorText\": \"...\", \"imagePrompt\": \"...\" }",
    "  ],",
    "  \"traits\": [",
    "    { \"id\": \"trait_id\", \"name\": \"...\", \"description\": \"...\" }",
    "  ],",
    "  \"appearance\": {",
    "    \"genderPresentation\": \"...\",",
    "    \"ageLook\": \"...\",",
    "    \"bodyType\": \"...\",",
    "    \"hair\": \"...\",",
    "    \"eyes\": \"...\",",
    "    \"outfit\": \"...\",",
    "    \"signatureFeature\": \"...\",",
    "    \"colorPalette\": \"...\",",
    "    \"mood\": \"...\"",
    "  },",
    "  \"portraitPrompt\": {",
    "    \"positive\": \"...\",",
    "    \"negative\": \"low quality, blurry, watermark\",",
    "    \"style\": \"fantasy RPG portrait\",",
    "    \"aspectRatio\": \"1:1\"",
    "  }",
    "}",
    "",
    buildCharacterSkillsPrompt(),
    "",
    "Rules:",
    "- skills array must contain exactly 3 skills.",
    "- starterEquipment should contain 1 starter weapon or armor.",
    "- starterEquipment items must include flavorText and imagePrompt.",
    "- traits must be objects with id, name, description.",
    "- portraitPrompt is only text for a future image workflow; do not call any image API.",
    "- Do not use generic slash/fireball/guard unless the user prompt asks for them.",
    "- First character must be { and last character must be }.",
    "- Return valid JSON only.",
    "- Do not use markdown.",
    "- Do not manually escape underscores, parentheses, Chinese characters, or punctuation.",
    "- Only use valid JSON escapes.",
    "- Avoid backslashes in descriptions unless necessary.",
    "- Use plain text strings.",
  ].join("\n");
}

module.exports = {
  buildCharacterPreviewPrompt,
};
