const { buildCharacterSkillsPrompt } = require("./buildCharacterSkillsPrompt");

function buildRuntimeAdventurePrompt(input = {}) {
  const genre = input.genre || "奇幻地下城";
  const characterPrompt = input.characterPrompt || "一位適合短篇冒險的角色";
  const adventurePrompt = input.adventurePrompt || "設計一段短篇地下城冒險。";
  const roomCount = Number(input.roomCount) || 5;
  const difficulty = Number(input.difficulty) || 4;
  const confirmedCharacter = input.confirmedCharacter;
  const starterEquipment = confirmedCharacter?.starterEquipment || confirmedCharacter?.equipment || [];

  return [
    "You are an RPG Content Designer. Output one valid JSON object only.",
    "Use Traditional Chinese for text fields. Use safe snake_case English ids.",
    "",
    "Character prompt:",
    characterPrompt,
    confirmedCharacter
      ? [
          "",
          "Confirmed character, adventure MUST use this character:",
          `name: ${confirmedCharacter.name}`,
          `title: ${confirmedCharacter.title || ""}`,
          `summary: ${confirmedCharacter.summary || ""}`,
          `attributes: ${JSON.stringify(confirmedCharacter.attributes || {})}`,
          `skills: ${JSON.stringify(confirmedCharacter.skills || [])}`,
          `starterEquipment: ${JSON.stringify(starterEquipment)}`,
        ].join("\n")
      : "",
    "",
    "Adventure input:",
    `genre: ${genre}`,
    `roomCount: ${roomCount}`,
    `difficulty: ${difficulty}/10`,
    adventurePrompt,
    "",
    "Root schema:",
    "- initialRoomId, winCondition, player, rooms, items, monsters, skills",
    "- rooms, items, monsters, and skills MUST be JSON object maps, not arrays.",
    "- object map keys MUST exactly match inner id fields.",
    "- player.skills MUST contain skill ids.",
    "- If a confirmed character is provided, player skills must match confirmedCharacter.skills.",
    "",
    "Room schema:",
    "{",
    "  \"id\": \"room_id\",",
    "  \"name\": \"...\",",
    "  \"description\": \"...\",",
    "  \"kind\": \"start\" | \"combat\" | \"puzzle\" | \"treasure\" | \"rest\" | \"key\" | \"boss\" | \"lore\",",
    "  \"ascii\": \"\",",
    "  \"exits\": { \"north\": \"other_room_id\" },",
    "  \"items\": [\"item_id\"],",
    "  \"monster\": \"monster_id_or_null\",",
    "  \"challenge\": null",
    "}",
    "",
    "Item schema:",
    "{",
    "  \"id\": \"item_id\",",
    "  \"name\": \"...\",",
    "  \"description\": \"...\",",
    "  \"type\": \"key\" | \"consumable\" | \"equipment\" | \"quest\" | \"material\",",
    "  \"usageHint\": \"use item_id\",",
    "  \"sourceType\": \"direct_pickup\" | \"puzzle_reward\" | \"monster_drop\" | \"sealed_chest\" | \"boss_reward\",",
    "  \"rarity\": \"common\" | \"uncommon\" | \"rare\",",
    "  \"flavorText\": \"...\",",
    "  \"imagePrompt\": \"...\"",
    "}",
    "- consumable items include effect.hp.",
    "- equipment items include slot and stats.",
    "- equipment slot must be weapon, armor, or accessory.",
    "",
    "Monster schema:",
    "{",
    "  \"id\": \"monster_id\",",
    "  \"name\": \"...\",",
    "  \"maxHp\": 20,",
    "  \"hp\": 20,",
    "  \"attack\": 5,",
    "  \"defense\": 1,",
    "  \"expReward\": 10,",
    "  \"drops\": [\"item_id\"],",
    "  \"description\": \"...\"",
    "}",
    "",
    buildCharacterSkillsPrompt(),
    "- Skill numeric display fields are required: mpCost, damage, hitCount, heal, shield, defenseBonus, duration.",
    "- Missing numeric fields should be 0, except hitCount should be 1.",
    "",
    "Challenge schema:",
    "{",
    "  \"type\": \"item_puzzle\" | \"locked_door\" | \"mechanism\" | \"trap\" | \"sealed_chest\",",
    "  \"description\": \"...\",",
    "  \"requiredItemId\": \"required_item_id\",",
    "  \"blockedExits\": [\"east\"],",
    "  \"unlocksExits\": [\"east\"],",
    "  \"solutionHint\": \"提示玩家使用 required_item_id，不要要求輸入文字答案\",",
    "  \"rewardItemIds\": [\"optional_reward_item_id\"],",
    "  \"unlocksExit\": { \"direction\": \"east\", \"roomId\": \"target_room_id\" },",
    "  \"unlocksRoom\": \"optional_room_id\"",
    "}",
    "",
    "Challenge rules:",
    "- Every challenge MUST be solved by using an item with command use item_id.",
    "- Every challenge MUST include requiredItemId, and that item MUST exist in items.",
    "- The required item MUST be obtainable before the challenge, not behind the same challenge.",
    "- Valid sources are direct pickup in an earlier/reachable room, earlier challenge reward, normal monster drop, or sealed chest reward.",
    "- Do NOT create riddle, answer_riddle, text_answer, guess, answer, solve, say, typed answer, or question-answer challenges.",
    "- Do NOT ask the player to type a word, phrase, password, or answer.",
    "- Use item_puzzle for any puzzle that is not specifically a locked door, mechanism, trap, or sealed chest.",
    "- If a challenge blocks movement, blockedExits must list only the blocked directions.",
    "- Do not block every exit unless the room is intentionally sealed and has a clear item solution.",
    "- Always leave at least one backtracking exit unblocked when possible.",
    "- If a challenge opens a path, unlocksExits should include the opened direction.",
    "- rewardItemIds must reference existing items.",
    "",
    "5-room pacing template:",
    "1. start room: intro and basic hint.",
    "2. combat or item_puzzle room: first obstacle.",
    "3. key or treasure room: equipment, key item, or useful consumable.",
    "4. rest/lore/mechanism room: preparation before Boss.",
    "5. boss room: Boss + quest item.",
    "",
    "If roomCount is 6-8, add optional treasure, puzzle, elite combat, or rest rooms before Boss.",
    "",
    "Design requirements:",
    "- At least 1 healing consumable.",
    "- At least 1 equipment item obtainable before the boss.",
    "- At least 1 item-based challenge.",
    "- At least 1 monster encounter and 1 boss encounter.",
    "- Boss guards winCondition.requiredItemId.",
    "- The adventure should reflect the confirmed character's skills and starter equipment when provided.",
    "",
    "Output rules:",
    "- Return valid JSON only.",
    "- First character must be { and last character must be }.",
    "- Do not use markdown.",
    "- Do not manually escape underscores, parentheses, Chinese characters, or punctuation.",
    "- Only use valid JSON escapes.",
    "- Avoid backslashes in descriptions unless necessary.",
    "- Use plain text strings.",
  ].join("\n");
}

module.exports = {
  buildRuntimeAdventurePrompt,
};
